### ISSUE TITLE
login fail : space in the user name

### ISSUE THREAD

**Issue by warlordattack** [hassio-addons/addon-uptime-kuma#11]
installes this HA addon on the last hass OS update,
added some hosts in uptime kuma, OK

1/ impossible to add integration to display my monitored hosts inside HA ?
this tuto : https://www.youtube.com/watch?v=9xBGO2Fpnkc&t=4s&ab_channel=BeardedTinker
sends to this read only repo to add to HACS : https://github.com/meichthys/uptime_kuma
but the repo si impossible to add in HACS, and sends to an other repo : 
https://github.com/jayakornk/pyuptimekuma
but this repo is impossible to add to HACS : https://github.com/jayakornk/pyuptimekuma/issues/1
😭😩

2/ impossible to login 
when installed addon i used ipad with his fu * * * g auto-completion i fight all the time,
and in the install process when created user for uptime kuma there is a fu * * * g space character at the end of the user name
uptime kuma created user with the space character,
the ipad recorded credentials, so no problemo to login with this user name on ipad,
but on hte PC, i typed the username without space so uptime kuma displayed the message : wrong user or password
after hours of trial and error, finally copy-pasted infos from ipad and noticed the fu * * * g space character !
and now i can login from PC :)

BUT : 
how do i change the user name in uptime kuma to correct my space error ???
there is only logout and change password options in this HA extension ?

help please xD

**Comment by lkamache** [comment]
Hello! Inside Uptime Kuma, you can download a backup, remove the addon, re-add it and then upload your backup. It does not contain your login credentials so you can create a new one in this install.
Hope this help.

**Comment by warlordattack** [comment]
thank you this worked well 👍

**Comment by lkamache** [comment]
Glad I could help
