### ISSUE TITLE
Issue updating kuma 0.9.1

### ISSUE THREAD

**Issue by ivorsmorenburg** [hassio-addons/addon-uptime-kuma#118]
# Problem/Motivation

> didnt update to 0.9.1

## Expected behavior

> to update without issues

## Actual behavior

> Can't install ghcr.io/hassio-addons/uptime-kuma/aarch64:0.9.1: 500 Server Error for http+docker://localhost/v1.43/images/ghcr.io/hassio-addons/uptime-kuma/aarch64:0.9.1/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")

## Steps to reproduce

just press update 

(How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by ivorsmorenburg** [comment]
Failed to to call /store/addons/a0d7b954_uptime-kuma/update - Can't install ghcr.io/hassio-addons/uptime-kuma/aarch64:0.9.1: 500 Server Error for http+docker://localhost/v1.43/images/ghcr.io/hassio-addons/uptime-kuma/aarch64:0.9.1/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")

**Comment by frenck** [comment]
> aarch64:0.9.1/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument

That is an issue with your system, not the add-on. This might be data corruption (if you are using an SD card, it might be failing. Or in the case of an RPi, you might have underpower).

Try running `ha supervisor repair` from a terminal window.

Closing the issue on this end, as this is not in the control or scope of an add-on.

../Frenck
