### ISSUE TITLE
Cloudflared should be included

### ISSUE THREAD

**Issue by AlexSwensen** [hassio-addons/addon-uptime-kuma#121]
# Problem/Motivation

Noticed cloudflared is not included in the addon. This is probably one of the easiest ways a user can setup a reverseproxy, especially within homeassistant. While its not required, it would lower the barrier to entry.

<img width="1650" alt="Screenshot 2023-11-09 at 11 47 43 AM" src="https://github.com/hassio-addons/addon-uptime-kuma/assets/7460917/314a7921-21e0-4363-a6f8-39a69672be01">

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

- Install a fresh copy of the addon
- setup your admin account
- navigate to reverse proxy setting

## Proposed changes

Add a working instance of cloudflared

**Comment by frenck** [comment]
Sorry, not planning no adding that. If you want to run a reverse proxy, one can use an dedicated add-on to do so.

../Frenck
