### ISSUE TITLE
Please add option to add kuma to the side board

### ISSUE THREAD

**Issue by kaystrobach** [hassio-addons/addon-uptime-kuma#134]
# Problem/Motivation

To reach kuma we have to click into settings > Addons > kuma > open user ui

## Expected behavior

Have a sidebar panel for uptime kuma, optimal would be with sso

## Actual behavior

no option to add it to the sidebar

## Steps to reproduce

install the addon

## Proposed changes

Add the option to add it to the sidebar like for code addon or file addon.

**Comment by frenck** [comment]
That is technically not possible until Uptime Kuma adds the possibility to support reverse proxies hosted in a subfolder. A feature request for that has been open for a long long time (and supported by many). Until that happens, this is a no go in this add-on (unfortunately).

../Frenck

**Comment by kaystrobach** [comment]
ok, thank you for clarification.
