### ISSUE TITLE
Unable to configure docker host monitoring

### ISSUE THREAD

**Issue by desosav** [hassio-addons/addon-uptime-kuma#14]
# Problem/Motivation

> Not able to monitor docker host

## Expected behavior

> Successfully add the docker host

## Actual behavior

> Error: Connect ENOENT /var/run/docker.sock

## Steps to reproduce

> In uptime-kuma go to settings--> docker hosts and try to setup a new host

## Proposed changes

> according to [this](https://github.com/louislam/uptime-kuma/wiki/How-to-Monitor-Docker-Containers) we need to bind the /var/run/docker.sock as read only

**Comment by frenck** [comment]
Yup, I'll update the readme to make the limitation clear.
The add-on cannot access Docker and will never be able to.

../Frenck

**Comment by tbgoose** [comment]
Wouldn't it be possible to run it in privileged mode and bind /var/run/docker.sock:/var/run/docker.sock like Portainer?

I guess there are risks but can make it a toggle in config and have a warning that only do it if you know what your are doing?
