### ISSUE TITLE
Home Assistant Operating System 11.4 (from 11.3) breaks Authentication

### ISSUE THREAD

**Issue by domenicdistefano** [hassio-addons/addon-uptime-kuma#145]
Previously I had to turn off authentication for the plugin to work (had been working for several months). Now after upgrading the OS to 11.4 authentication is broken completely which also makes any existing / associated entities disappear. 

I am running on a VM so luckily made a snapshot before the upgrade and after rolling back everything is back to working - for now....

**Comment by sinclairpaul** [comment]
Are you referring to the integration or addon?

**Comment by domenicdistefano** [comment]
Oops, I may have posted this at the wrong place / put this problem at your door by mistake. Its the integration. The add-on (where I believe you run the instance of the app itself) runs fine. The integration fails authenticating to the add-on or a regular instance outside of HA,
