### ISSUE TITLE
Missing options for iframe and Server environment variables

### ISSUE THREAD

**Issue by williamhelle** [hassio-addons/addon-uptime-kuma#15]
# Problem/Motivation

> Missing options in hassio/addon/abbbbbbb_uptime-kuma/config

## Expected behavior

> Setting up the addon

## Actual behavior

> No options other than Network webgui port.

## Steps to reproduce

> N/A

## Proposed changes

> Add them for more customization in settings
> Add ssl options for https protocol 
Thanks ;)

**Comment by frenck** [comment]
> Add them for more customization in settings

I have no intention of adding those. Instead, we are awaiting an upstream change that allows the use of the Ingress feature, which is much more valuable.

> Add ssl options for https protocol

If you need SSL, please use a reverse proxy that handles that.

**Comment by williamhelle** [comment]
Wow you fast 😂 no problem for ssl just thinking that was cool for some user, question, is it possible to create a private addon of it and add these ?

**Comment by frenck** [comment]
> for ssl just thinking that was cool for some user

It isn't. In the past, many add-ons had those options. However, it has side-effects. For example, the need to restart add-ons when certificates change. In general, offloading SSL using a proxy is much easier, and better and greatly reduces the complexity of an add-on.

All my add-on, that currently still have SSL configuration options, will get them removed in the future.

> is it possible to create a private addon of it and add these ?

Whatever you like 🤷

**Comment by tjorim** [comment]
Everything is possible 😉 feel free to fork this repo and make the changes.
![Screenshot_2022-09-24-18-17-58-53_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/1294876/192108318-a4b73d15-7a74-4891-acad-499927a970e4.jpg)

**Comment by williamhelle** [comment]
Ok, thanks, so no problem to forking project ;) I will do this
I will send a pull request if I do an ENORMOUS maj 😂
Have a good day ;)

**Comment by williamhelle** [comment]
I try, just use vim and insert true on false, type CTRL+C :w and :q, restart my addon to change variable 😂
I understand your laziness to code this, should rework all to make it live, so yeah my idea is stupid sorry ;)

**Comment by frenck** [comment]
> I will send a pull request 

As said above, I have no interest in adding that feature. Please don't bother opening a pull request for that.

**Comment by williamhelle** [comment]
Okay, thanks ;) 
I'm new in docker coding, so I'm dumb 😂
Good coding for next addons ;)
