### ISSUE TITLE
Add to Sidebar?

### ISSUE THREAD

**Issue by macjeff** [hassio-addons/addon-uptime-kuma#152]
New to Home Assistant.   There is no SHOW ON SIDEBAR button.

Can you help with the config to make it work or post update?

Thanks!!

**Comment by frenck** [comment]
Unfortunately, this is not possible yet. We are waiting for support for reverse proxies hosting Uptime Kuma in subfolders (which is basically what Ingress is).

Until that isn't supported upstream, there is not much we can do.

../Frenck

**Comment by emosenkis** [comment]
Upstream issue: https://github.com/louislam/uptime-kuma/issues/147
