### ISSUE TITLE
Uptime Kuma entities not available in HA

### ISSUE THREAD

**Issue by xelemorf** [hassio-addons/addon-uptime-kuma#156]
# Problem/Motivation

> UptimeKuma sensor entities dissapeared in HA, showing "Error in describing condition: can't access property "entity_id" of undefined"; manual check for entity availability shows no custom UptimeKuma monitors are populated into HA.

## Expected behavior

> Custom UptimeKuma monitors should be auto-populated after addon-start

## Actual behavior

> UptimeKuma sensor entities dissapeared in HA, only the below are available, none of the custom monitors are available

- Uptime Kuma Running
- uptimekuma ha local

## Steps to reproduce

> Let UptimeKuma run for over 90 days with 28 monitor entities, wait for the database to grow over 2GB (2397.6 GB) While settings are configured to keep only 1 day history.

## Proposed changes

> Vacuum function clearly not working: "Trigger database VACUUM for SQLite. If your database is created after 1.10.0, AUTO_VACUUM is already enabled and this action is not needed."
This is a re-occurring issue once the database grows above 2GB, having a setting to keep history for 1 days does not do anything.

## Current workaround (reinstall UptimeKuma)

>1. Export all settings manually (since the backup feature does not work and you cannot access the data folder for UptimeKuma on HAOS)
>2. Completely uninstall UptimeKuma addon and integration, cleanup all relevant folders (\\ha\config\custom_components\uptime_kuma\)
>3. Reboot HAOS
>4. Reinstall Uptime Kuma Addon and HA integration, reboot HAOS
>5. Reconfigure everything from scratch using the same monitor names and settings
>6. Configure database to keep only 1 days of history, observe the second day that th setting is not respected
>7. Wait for some time to the database to grow above 2GB then rinse and repeat all the steps 

## System details:
>HomeAssistant Addon version: 0.12.0
>HAOS OVA (VMware) - The issue is independent from HAOS and HA versions.
>Core 2024.2.2
>>Supervisor 2024.01.1
Operating System 11.5
>Frontend 20240207.1
>CPU: 2 vCPU (Intel Core i7-8700T @ 2.40GHz)
>RAM: 4GB (DDR4)

**Comment by frenck** [comment]
I think you are mixing up things.

This is the Uptime Kuma add-on, not integration...

Please report your issue with the integration author instead.

../Frenck

**Comment by xelemorf** [comment]
> I think you are mixing up things.
> 
> This is the Uptime Kuma add-on, not integration...
> 
> Please report your issue with the integration author instead.
> 
> ../Frenck

This seems to me an issue with the addon, not the integration. If I perform a clean reinstall of the addon that solves the issue. I suspeect this is related to the database size on the addon side, this is my second time with this issue, seems to trigged when database is above 2GB.

**Comment by xelemorf** [comment]
Can you please advise what logs to provide to be able to effectively investigate the issue before I do a clean reinstall of the addon and losing all the relevant logs?

**Comment by frenck** [comment]
Any error in the integration is not a concern for that add-on.

As said, if you have issue with the integration, please report it with the custom integration author.

../Frenck

**Comment by xelemorf** [comment]
Bugreport created for the integration: https://github.com/louislam/uptime-kuma/issues/4502
