### ISSUE TITLE
How do we backup this?

### ISSUE THREAD

**Issue by oriold** [hassio-addons/addon-uptime-kuma#160]
# Problem/Motivation

>I want to take a backup, according to the instructions in the addon you just need to backup /data/ directory. Where is directory located/exposed?

## Expected behavior

> We need a way to backup the info from this addon, otherwise is a bit risky.

## Actual behavior

> Backup procedure is not documented

## Proposed changes

>Document how to backup this/ inform that it doesn't have backups available.

**Comment by sinclairpaul** [comment]
It's a function of the Home Assistant platform, not the addon, if you navigate to Settings/System/Backups you can generate one from there.
