### ISSUE TITLE
Data location?

### ISSUE THREAD

**Issue by AJolly** [hassio-addons/addon-uptime-kuma#167]
Where exactly is this storing its data? 

It suggests backing up .data, but it doesnt seem to be exposing it to the host.
"Deprecated: Since a lot of features were added and this backup feature is a bit unmaintained, it cannot generate or restore a complete backup.

Please backup the volume or the data folder (./data/) directly instead."

**Comment by frenck** [comment]
It stores the data in the /data folder that the Home Assistant Supervisor provides. Home Assistant manages and creates this, and also takes care of backing it up.

Where it is originating from, is not a concern for the add-on.

../Frenck
