### ISSUE TITLE
Using SSL 

### ISSUE THREAD

**Issue by bditter** [hassio-addons/addon-uptime-kuma#184]
# Problem/Motivation

> Add-on only responds to http

## Expected behavior

> The ability to add SSL certificate and access via HTTPS

## Actual behavior

> Give err: Connection is not secure. ERR_SSL_PROTOCOL_ERROR

## Steps to reproduce

> Load with site using https instead of http

## Proposed changes

> Allow the add-on to upload certificate(s) and key files to the necessary location. Add the option to turn on and/or require SSL connection.

**Comment by tjorim** [comment]
Duplicate issue, please use a reverse proxy for this.

**Comment by bditter** [comment]
None of those are applicable since I'm running on a Raspberry Pi and have my own third party SSL certificates and domains and use those to secure my HA instance. Redirecting my functioning domain to Cloudflare is not an acceptable option.

**Comment by frenck** [comment]
Nobody said Cloudflare.

If you need to terminate an application with SSL, the use of a reverse proxy (any you like) is recommended.

../Frenck
