### ISSUE TITLE
Add Ingress

### ISSUE THREAD

**Issue by Gooman-rus** [hassio-addons/addon-uptime-kuma#188]
# Problem/Motivation

> I need to be able to load addon page via button on the side panel.

## Expected behavior

> Ingress is configured for this addon. There is an ability to set up button on the side panel.

## Actual behavior

> Ingress is not configured. Unable to set up button for the panel due to CORS policy.

## Steps to reproduce

> Install addon.

**Comment by frenck** [comment]
This is not possible due to a technical limitation in Uptime Kuma.

../Frenck
