### ISSUE TITLE
Password default

### ISSUE THREAD

**Issue by epinto** [hassio-addons/addon-uptime-kuma#198]
Hate to say it, but I did my RTFM duty.  The add-on is not taking the admin/password default that I see in the Uptime Kuma documentation. The README didn't specify it either. This is a brand new 'install' of the add-on, what is the default user and password?

I also tried my HASS username and login, just to make sure, that wasn't it.

### Discussed in https://github.com/hassio-addons/addon-uptime-kuma/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **JeromeDevome** June 13, 2022</sup>
Hello,
Thanks again for this addon.
What is the default password?

</div>

**Comment by reenberg** [comment]
I just went through resetting my admin password.

It appers that this container version mounts the data directory, where uptime-kuma stores its database inside /data, but installs the app inside /opt/uptime-kuma/, which renders the default `npm run reset-password` useless.  Luckily they added a way to overrule the location of the data directory at some point so you can do the following:

```bash
# In the homeassistant shell do the following
$ docker ps | grep uptime-kuma

# Use the name of the running uptime-kuma container
$ docker exec  -it <addon_XXX_uptime-kuma> bash

# Now inside the container, change dir to where the uptime-kuma code is located
cd /opt/uptime-kuma

# Run the reset-password command, setting the DATA_DIR environment variable, such that the reset command can actually locate the database.
env DATA_DIR=/data/ npm run reset-password

# The reset-password command will now ask you for a new admin password.
```

@frenck , perhaps this little detail could be added to the readme, so it would show when reading the add-on documentation inside homeassistant, as you won't find it easily in the uptime-kuma documentation.

**Comment by frenck** [comment]
@reenberg I've hidden your comment. The procedure you describe is not supported and most certainly not recommended. Please note that you might lure people who have no knowledge of this subject into places they shouldn't be in. If something goes wrong, they might do more damage.

../Frenck

**Comment by reenberg** [comment]
@frenck, fair, but due elaborate on what parts you mean aren't supported? 

The npm command was taken from the upstream project, so it's would seem perfectly supported?

**Comment by frenck** [comment]
You should be sending users into HA Supervisor managed docker containers. one reason many people run Home Assistant OS is because they don't have the technical knowledge on this level. See my previous answer.

**Comment by MichaelSchaaf999** [comment]
Frenck: Is there a solution to the question about the standard user and password?
Today I found that all of a sudden the AddOn is prompting me for these credentials I can't remember to have setup a couple of days ago. And no "forgot my password" to reset is shown either.
What do you recommend? I am a noob and don't want to dive deep into Unix things, just operating via GUI is fine for me.
Kind regards
Micha
