### ISSUE TITLE
Uptime Mate

### ISSUE THREAD

**Issue by swtharp** [hassio-addons/addon-uptime-kuma#203]
I want to use Uptime Mate which is a way to view UPtime_Kuma on my Apple Watch. The app requires you to add -TOKEN=xxxx to the docker-compose.yml file. 

> I do not see a way to add this to the Uptime-Kuma Web App

## Proposed changes

If this could be added to your HomeAssistant configuration that woudl resolve my issues

**Comment by sinclairpaul** [comment]
From a quick google, I believe the watch app requires additional software to run, see <https://github.com/schech1/uptime-buddy>

Therefore it wouldn't be functional with just Uptime Kuma itself.

**Comment by swtharp** [comment]
I have everything in place just fils because the Uptime does not have the
tolken value set.

Steven

**Comment by sinclairpaul** [comment]
Well looking at the documentation the token comes from the app <https://github.com/schech1/uptime-buddy?tab=readme-ov-file#prerequisites-in-the-uptime-mate-ios-app>

**Comment by swtharp** [comment]
Yes the app creates the tolken then you add it to the docker-compose.yml
and restart the Uptime-Kuma it is a method for the watch to login to the
server.

Steven Tharp

**Comment by sinclairpaul** [comment]
I think you should re-read the instructions, the linked app requires an additional Docker container to run, in addition to Uptime Kuma.  That is the referenced Docker Compose, running the Uptime Mate container, not Uptime Kuma <https://github.com/schech1/uptime-buddy?tab=readme-ov-file#docker-compose>

This really is unrelated to the addon itself, as no changes are done to Uptime Kuma.
