### ISSUE TITLE
[Feature request] Show in sidebar option

### ISSUE THREAD

**Issue by kriakiku** [hassio-addons/addon-uptime-kuma#205]
Hey! Thanks for this plugin. Could you consider adding a "Show in sidebar" option in the plugin settings?

Example:
![example](https://github.com/user-attachments/assets/4f02ecfc-8741-4fa5-8ae4-3e40eaf6ae9e)

**Comment by frenck** [comment]
This is not possible due to technical limiting in uptime kuma. There is an upstream feature request open to make this possible:


../Frenck
