### ISSUE TITLE
Uptime Kuma cannot be set to use https ?

### ISSUE THREAD

**Issue by Kilowatt-W** [hassio-addons/addon-uptime-kuma#26]
# Problem/Motivation

> When trying to use the Uptime Kume Integration its not possibel to switch the Addon to ssl and use the homeassistant certificates ?

## Expected behavior

> Like in some other addons it would be nice to use the onboard certs and provide ssl for https

## Actual behavior

> Uptime Addon is coming up on default port 3001 but with http

## Steps to reproduce

> Install and start "normal" addon

Maybe this would be a nice feature or it was forgotten at building the Image :-)

Greetings,

from Austria

Kilowatt

**Comment by tjorim** [comment]
If you need SSL, please use a reverse proxy that handles that.

**Comment by frenck** [comment]
As per above 👍
