### ISSUE TITLE
Please add the option to Show in Sidebar

### ISSUE THREAD

**Issue by csweinberg** [hassio-addons/addon-uptime-kuma#27]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by csweinberg** [comment]
Please add the option to Show in Sidebar

**Comment by lkamache** [comment]
Not possible as explained by Frenck himself on another thread

**Comment by frenck** [comment]
As per above, this is a technical limitation created by Uptime Kuma itself. There is nothing we can do about it.

../Frenck
