### ISSUE TITLE
No mqtt:// service available for Apprise notifications

### ISSUE THREAD

**Issue by TroLoos** [hassio-addons/addon-uptime-kuma#28]
# Problem/Motivation

No MQTT available.

## Expected behavior

MQTT included in docker image.

## Actual behavior

When trying to set up Apprise notification via MQTT, the following error appears:

ERROR - mqtt:// is disabled on this system.

## Steps to reproduce

See above.

## Proposed changes

Change Uptime Kuma docker image to one, that includes MQTT.

**Comment by frenck** [comment]
Thanks! 👍 

That is indeed an issue with the add-on. I've prepared a fix for he next release of the add-on.

../Frenck
