### ISSUE TITLE
The addon doesn't open web interface with ingress

### ISSUE THREAD

**Issue by Enzokot** [hassio-addons/addon-uptime-kuma#3]
# Problem/Motivation
The addon doesn't open web interface with ingress
> (Why the issue was filed)

## Expected behavior
The addon opens its own web interface with ingress
> (What you expected to happen)

## Actual behavior
The addon doesn't open web interface with ingress
> (What actually happened)

## Steps to reproduce
Click on the "open web ui" button
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
That is correct and not a bug.

Unfortunately, Due to technical limitations in Uptime Kuma, it is impossible to provide Ingres support to the Uptime Kuna add-on.
