### ISSUE TITLE
Can't embed to iFrame

### ISSUE THREAD

**Issue by marciogranzotto** [hassio-addons/addon-uptime-kuma#4]
# Problem/Motivation

By default, Uptime Kume doesn't allow being embedded in an iframe. Because of that, it cannot be added to the Home Assistant sidebar.

## Expected behavior

Being able to access it from the sidebar

## Actual behavior

Doesn't work

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

A `UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN` environment variable can be set to allow embedding in an iframe.

**Comment by DavidJuanes** [comment]
Can this ticket be re-opened? I'd like to know if @marciogranzotto proposed solution would work to have uptime kuma in HA sidebar

**Comment by marciogranzotto** [comment]
> Can this ticket be re-opened? I'd like to know if @marciogranzotto proposed solution would work to have uptime kuma in HA sidebar

yes, I'm using my fork as a local add-on on my instance
