### ISSUE TITLE
deprecated call async_setup_platforms 

### ISSUE THREAD

**Issue by azlux** [hassio-addons/addon-uptime-kuma#42]
Hi,
The current version of kuma HACS integration (v2.0.2) print an error into the home-assistant console.

> WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for uptime_kuma using this method at custom_components/uptime_kuma/__init__.py, line 52: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

It's still working well, but to avoid a futur issue, a change will be necessary.

Azlux

**Comment by frenck** [comment]
Cool, this is, however, not an integration, but an add-on.

I think you are mixing things up. Closing this issue as it is for sure not related to this add-on.

../Frenck

**Comment by azlux** [comment]
Oups, srry it's indeed not the good project.
