### ISSUE TITLE
No access to tailscale

### ISSUE THREAD

**Issue by hacketaler** [hassio-addons/addon-uptime-kuma#43]
# Problem/Motivation

using uptime kuma to monitor network. HA is also connected to tailscale via hassio-addon tailscale.
but uptime kuma is not able to check (ping) other tailscale-devices (like mobile phones)

## Expected behavior

kuma should bei able to check on all networks

## Actual behavior

not using tailscale-network provided by other hassio-addon

## Steps to reproduce

using a monitor to ping a tailscale-ip

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
That would be correct and expected behavior not an bug of this addon.

../Frenck
