### ISSUE TITLE
Push Monitor Doesn't Update in Home Assistant but updates in Uptime Kuma

### ISSUE THREAD

**Issue by banana-king778** [hassio-addons/addon-uptime-kuma#44]
# Problem/Motivation

> In the web interface/Uptime Kuma it shows the push monitor up. However, in Home assistant it says disconnected, sometimes it updates, and sometimes it doesn't. There appears to be some sort of disconnect between Home Assistant and Uptime Kuma, but just for the push monitor, I have other HTTP monitors and they work fine in HA and Uptime Kuma.

## Expected behavior

> Home Assistant entity to update and show the correct information from Push Monitor from Uptime Kuma.

## Actual behavior

> Home Assistant entity does not update and seems disconnected from Push Monitor from Uptime Kuma. However, as I said my other HTTP monitors within Uptime Kuma update correctly and work as expected. The only problem is with the Push Monitor.

## Steps to reproduce

> Set up a push monitor and see if it works in Home Assistant.

## Proposed changes

> I don't have a fix, there appears to be some sort of disconnect between Uptime Kuma's push monitor and the home assistant entity, I don't know how this addon works, so not much help from me.

**Comment by frenck** [comment]
> Home Assistant entity to update and show the correct information from Push Monitor from Uptime Kuma.

Add-ons do not provide entities. You are mixing up integrations vs add-ons. As this is the add-on, I'm going to close the issue.

../Frenck
