### ISSUE TITLE
Uptime Kuma Home Assistant and Nabu Casa

### ISSUE THREAD

**Issue by dharvey242** [hassio-addons/addon-uptime-kuma#48]
Will the Uptime Kuma Integration work with Home Assistant via the Nabu Casa URL i.e. https://[nabuacasaurl]:[uptimekumaport]

I get a server 500 error when I try. 

if not how do I configure the Integration to work with another reverse proxy url?

**Comment by frenck** [comment]
> if not how do I configure the Integration to work with another reverse proxy URL?

You don't. This integration doesn't support ingress. 

../Frenck
