### ISSUE TITLE
Fail to load with HomeAssistant 2023.3

### ISSUE THREAD

**Issue by nickmarko** [hassio-addons/addon-uptime-kuma#53]
# Problem/Motivation

> After HA 2023.3 core update, uptime kuma loading fails with error message "Requirements for uptime_kuma not found: ['pyuptimekuma==0.0.6']."

## Expected behavior

> Integration / Add-on to load

## Actual behavior

> Does not load with above error

## Steps to reproduce

> Update HA to core 2023.3 and attempt to load uptime kuma add-on / plugin

## Proposed changes

Change or update dependency

**Comment by frenck** [comment]
You are mixing up add-ons vs integrations.

This is **not** an Home Assistant integration, but an add-on. You are in the wrong place.

../Frenck
