### ISSUE TITLE
PIP problem 

### ISSUE THREAD

**Issue by Heelderpeel** [hassio-addons/addon-uptime-kuma#56]
Hello, i got this error, someone any idee what to do, and how.
(Hassio install.)

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 01:07:56 (3 occurrences)
Last logged: 01:08:01

Unable to install package pyuptimekuma==0.0.6: ERROR: Cannot install pyuptimekuma==0.0.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by sinclairpaul** [comment]
#53 
#52 
#51 


Please do search before logging an issue, your problem is with the custom integration not the addon.  I believe the source of the custom integration that you have installed is likely at <https://github.com/meichthys/uptime_kuma> so would suggest asking there.

**Comment by Heelderpeel** [comment]
sorry guys, for me thats not so clear, i am not a expert.
Whats te sign for me thats it the integration en not the addon?
Never to old to learn

**Comment by frenck** [comment]
> Whats te sign for me thats it the integration en not the addon?

When it is the add-on or the integration 🤷 

I'm not sure what to answer here... those are simply not the same things.

**Comment by Heelderpeel** [comment]
I do understand the difference between an addon and an integration, but what in the above error tells me whether it is from the addon or from the integration.
For example, if it says package, is it always an integration?

**Comment by frenck** [comment]
The error above is from Home Assistant...

**Comment by frenck** [comment]
> oke, so its not that easy to see for me.

?! The error is from Home Assistant... not Uptime Kuma. How is that not easy to see?

**Comment by Heelderpeel** [comment]
oo wait misunderstanding, so if it comes from the addon there is no home assistant in the error, or am I misunderstanding that.
