### ISSUE TITLE
Can't set log-level

### ISSUE THREAD

**Issue by andriej** [hassio-addons/addon-uptime-kuma#6]
# Problem/Motivation

> Currently there is no way to set log-level to any othe (default: INFO)

## Expected behavior

> Possible to set log-level

## Actual behavior

> INFO log level is massive if a lot of sensors set

## Steps to reproduce

> Start addon and add >20 monitos

## Proposed changes

> Add log_level option to lower the amount of not necessay information

**Comment by frenck** [comment]
That log_level option would only apply to the add-on itself (not Uptime Kuma), anything, in particular, you are trying to do?

**Comment by andriej** [comment]
Right, I forgot it's add-on log level not program itself.
I'm trying to silence it a little (at least WARN level), as I have a lot of monitors and seeing every each of them ran without problems is not something I need to see in logs.

**Comment by frenck** [comment]
Could you share an example(s) of such logs?

**Comment by andriej** [comment]
I must have missed log behavior of add-on - it prompts only message regarding set-up, not every run of monitor.
Closing the issue.
