### ISSUE TITLE
Error notification in HA

### ISSUE THREAD

**Issue by mauriceatkinson** [hassio-addons/addon-uptime-kuma#61]
# Problem/Motivation
Home Assistant raises a notification that Upotimekuma could not be setup correctly
## Expected behavior
I expect no Home Assistant error notification

## Actual behavior
Logger: homeassistant.setup
Source: setup.py:205
First occurred: 07:46:38 (1 occurrences)
Last logged: 07:46:38

Setup failed for custom integration uptime_kuma: Requirements for uptime_kuma not found: ['pyuptimekuma==0.0.6'].
)

## Steps to reproduce
This notification error occurs each time Uptimekuma addon is restarted

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Cool, however, this is not an Home Assistant integration, you are in the wrong place.

../Frenck
