### ISSUE TITLE
Uptime Kuma status pages from the add-on won't display in a lovelace web page card.

### ISSUE THREAD

**Issue by bcGITster** [hassio-addons/addon-uptime-kuma#88]
## Proposed changes

Add UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=TRUE to the environment

**Comment by frenck** [comment]
Except, that won't work.

Thanks for the suggestion, but it lacks reasoning and actual understanding of the feature you like to use.

Closing.

../Frenck
