### ISSUE TITLE
[Feature Request] Support Kuma SSL Certificates

### ISSUE THREAD

**Issue by bryanyork** [hassio-addons/addon-uptime-kuma#93]
# Problem/Motivation
Uptime Kuma Supports SSL Certificates Natively
https://github.com/louislam/uptime-kuma/wiki/Environment-Variables#server-environment-variables

I would like to utilize Let's Encrypt SSL certificates similar to the Nginx Addon, but to load Uptime Kuma utilizing SSL.

I'd be willing to create a PR, but less familiar with how I can modify the addon to request a path for the certificate and key files.

**Comment by frenck** [comment]
I’ve been removing SSL support from all add-ons. Please use an reverse proxy to offload SSL instead.

../Frenck
